### ISSUE TITLE
Barnes Hut

### ISSUE THREAD

**Issue by Philip-Spaeth** [Philip-Spaeth/N-Body-Galaxy-Simulation#2]

**Comment by Kimneyyy** [comment]
Aktueller Fehler:
Bevor Partikel neu eingeteilt werden, checken, wo sich die Partikel im Bereich befinden.

Wenn alle Partikel in einem Bereich in einer Ecke → unnötig lange Verschachtelung.

Lösung:
Bereich vor jeder Zuteilung checken. Gegebenenfalls neues Rechteck erstellen um Zentrum.
